### ISSUE TITLE
Links to References

### ISSUE THREAD

**Issue by cgwillison** [sidewalklabs/doppelganger#18]
Using Chrome Version 58.0.3029.110 (64-bit), I wasn't able to access either the first or second references cited as inspiration for Doppleganger.  First link just never resolved and second link said "unable to load document" (however, dialog box offered option to reload and it worked the second time).

**Comment by DavidOry** [comment]
Thanks for letting us know. 

The first link is [http://dl.acm.org/citation.cfm?id=52121](http://dl.acm.org/citation.cfm?id=52121) and *appears* to be responsive on our end.

The second link is [http://docs.trb.org/prp/15-5343.pdf](http://docs.trb.org/prp/15-5343.pdf) and also *appears* to be responsive.

Are these the two you are referring to?

**Comment by cgwillison** [comment]
Yes, those are the ones.  I was able to finally open the pdf and I think I just needed to be extra patient with the ACM publication. Thanks.

**Comment by DavidOry** [comment]
Super.
