### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by ahardjasa** [sidewalklabs/doppelganger#20]
I'm not sure if Python 3 support is in your plans, but if so, I ran into a few issues when trying to run this package under Python 3.6:

- `unicode` (used in `inputs.py`) is not supported in Python 3. I think this can be addressed by adding `from builtins import str` and replacing `unicode` with `str`.

- `xrange` (used in `bayesnets.py`) is not supported in Python 3. Could either do `from builtins import range` and replace `xrange` with `range` or use `from past.builtins import xrange`.

**Comment by katbusch** [comment]
Thanks for the report @ahardjasa! We don't currently have plans to support python 3 but I don't think it would be very hard so I'll try to look into soon.

**Comment by katbusch** [comment]
Also feel free to submit a pull request :)
