### ISSUE TITLE
Pomegrenate issues on CentOS 7.3

### ISSUE THREAD

**Issue by camidusinc** [sidewalklabs/doppelganger#23]
Trying to get my setup working. I am running the pip install command on a CentOS server. 
I checked my gcc version and it does not require an upgrade at the moment:

[camidus@urbanizer doppelganger]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

**Errors returned below:** 

`  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/base.c -o build/temp.linux-x86_64-2.7/pomegranate/base.o
  In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                   from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pomegranate/base.c:444:
  /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pomegranate/base.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/pomegranate/base.so
  building 'pomegranate.BayesianNetwork' extension
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/BayesianNetwork.c -o build/temp.linux-x86_64-2.7/pomegranate/BayesianNetwork.o
  In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                   from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pomegranate/BayesianNetwork.c:444:
  /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pomegranate/BayesianNetwork.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/pomegranate/BayesianNetwork.so
  building 'pomegranate.FactorGraph' extension
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/FactorGraph.c -o build/temp.linux-x86_64-2.7/pomegranate/FactorGraph.o
  In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                   from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pomegranate/FactorGraph.c:444:
  /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pomegranate/FactorGraph.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/pomegranate/FactorGraph.so
  building 'pomegranate.distributions' extension
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/distributions.c -o build/temp.linux-x86_64-2.7/pomegranate/distributions.o
  In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                   from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pomegranate/distributions.c:444:
  /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pomegranate/distributions.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/pomegranate/distributions.so
  building 'pomegranate.fsm' extension
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/fsm.c -o build/temp.linux-x86_64-2.7/pomegranate/fsm.o
  gcc: error: pomegranate/fsm.c: No such file or directory
  gcc: fatal error: no input files
  compilation terminated.
  error: command 'gcc' failed with exit status 4

  ----------------------------------------
  Failed building wheel for pomegranate
  Running setup.py clean for pomegranate
Failed to build pomegranate
Installing collected packages: pomegranate, chardet, idna, urllib3, requests, doppelganger
  Running setup.py install for pomegranate ... error
    Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hVt89H/pomegranate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iPa6Ki-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pomegranate
    copying pomegranate/__init__.py -> build/lib.linux-x86_64-2.7/pomegranate
    running build_ext
    building 'pomegranate.base' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/pomegranate
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/base.c -o build/temp.linux-x86_64-2.7/pomegranate/base.o
    In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pomegranate/base.c:444:
    /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pomegranate/base.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/pomegranate/base.so
    building 'pomegranate.BayesianNetwork' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/BayesianNetwork.c -o build/temp.linux-x86_64-2.7/pomegranate/BayesianNetwork.o
    In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pomegranate/BayesianNetwork.c:444:
    /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pomegranate/BayesianNetwork.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/pomegranate/BayesianNetwork.so
    building 'pomegranate.FactorGraph' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/FactorGraph.c -o build/temp.linux-x86_64-2.7/pomegranate/FactorGraph.o
    In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pomegranate/FactorGraph.c:444:
    /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pomegranate/FactorGraph.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/pomegranate/FactorGraph.so
    building 'pomegranate.distributions' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/distributions.c -o build/temp.linux-x86_64-2.7/pomegranate/distributions.o
    In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pomegranate/distributions.c:444:
    /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pomegranate/distributions.o -L. -lpython2.7 -o build/lib.linux-x86_64-2.7/pomegranate/distributions.so
    building 'pomegranate.fsm' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -c pomegranate/fsm.c -o build/temp.linux-x86_64-2.7/pomegranate/fsm.o
    gcc: error: pomegranate/fsm.c: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'gcc' failed with exit status 4

    ----------------------------------------
Command "/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hVt89H/pomegranate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iPa6Ki-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hVt89H/pomegranate/
`

**Comment by katbusch** [comment]
Interesting.  Thanks for the report.  What version of numpy are you using and how did you install it?

**Comment by camidusinc** [comment]
I am running numpy 1.13.0

[camidus@urbanizer ~]$ pip freeze | grep numpy
numpy==1.13.0

I installed it by running: pip install numpy

**Comment by katbusch** [comment]
We recommend installing numpy with [Anaconda](https://www.continuum.io/downloads) or [another pre-built option](https://www.scipy.org/install.html).   Otherwise it can be quite a difficult and tedious process to get it build.

**Comment by camidusinc** [comment]
Thanks @katbusch , Anaconda was also installed but not correctly. I removed both numpy and Anaconda and reinstalled Anaconda 2. Now everything is fine, installation was successful: 
`
[root@urbanizer doppelganger]# pip install .
Processing /home/camidus/doppelganger
Collecting cvxpy==0.4.8 (from doppelganger==0.1.0)
Requirement already satisfied: numpy>=1.11.0 in /root/anaconda2/lib/python2.7/site-packages (from doppelganger==0.1.0)
Requirement already satisfied: pandas>=0.19.0 in /root/.local/lib/python2.7/site-packages (from doppelganger==0.1.0)
Collecting pomegranate>=0.7.1 (from doppelganger==0.1.0)
  Using cached pomegranate-0.7.3.tar.gz
Requirement already satisfied: requests>=2.0.0 in /root/anaconda2/lib/python2.7/site-packages (from doppelganger==0.1.0)
Requirement already satisfied: six>=1.10.0 in /root/.local/lib/python2.7/site-packages (from doppelganger==0.1.0)
Collecting scs>=1.1.3 (from cvxpy==0.4.8->doppelganger==0.1.0)
Collecting multiprocess (from cvxpy==0.4.8->doppelganger==0.1.0)
Collecting CVXcanon>=0.0.22 (from cvxpy==0.4.8->doppelganger==0.1.0)
Collecting ecos>=2 (from cvxpy==0.4.8->doppelganger==0.1.0)
Requirement already satisfied: toolz in /root/anaconda2/lib/python2.7/site-packages (from cvxpy==0.4.8->doppelganger==0.1.0)
Requirement already satisfied: scipy>=0.15 in /root/.local/lib/python2.7/site-packages (from cvxpy==0.4.8->doppelganger==0.1.0)
Requirement already satisfied: fastcache in /root/anaconda2/lib/python2.7/site-packages (from cvxpy==0.4.8->doppelganger==0.1.0)
Requirement already satisfied: pytz>=2011k in /root/.local/lib/python2.7/site-packages (from pandas>=0.19.0->doppelganger==0.1.0)
Requirement already satisfied: python-dateutil in /root/.local/lib/python2.7/site-packages (from pandas>=0.19.0->doppelganger==0.1.0)
Collecting joblib>=0.9.0b4 (from pomegranate>=0.7.1->doppelganger==0.1.0)
  Using cached joblib-0.11-py2.py3-none-any.whl
Requirement already satisfied: networkx>=1.8.1 in /root/anaconda2/lib/python2.7/site-packages (from pomegranate>=0.7.1->doppelganger==0.1.0)
Collecting dill>=0.2.6 (from multiprocess->cvxpy==0.4.8->doppelganger==0.1.0)
Requirement already satisfied: decorator>=3.4.0 in /root/anaconda2/lib/python2.7/site-packages (from networkx>=1.8.1->pomegranate>=0.7.1->doppelganger==0.1.0)
Building wheels for collected packages: pomegranate
  Running setup.py bdist_wheel for pomegranate ... done
  Stored in directory: /root/.cache/pip/wheels/e7/32/98/8b89b0775c143e2520ac966981c0382c77c45723caf0cccf6a
Successfully built pomegranate
Installing collected packages: scs, dill, multiprocess, CVXcanon, ecos, cvxpy, joblib, pomegranate, doppelganger
  Running setup.py install for doppelganger ... done
Successfully installed CVXcanon-0.1.1 cvxpy-0.4.8 dill-0.2.6 doppelganger-0.1.0 ecos-2.0.4 joblib-0.11 multiprocess-0.70.5 pomegranate-0.7.3 scs-1.2.6
[root@urbanizer doppelganger]#
`

**Comment by katbusch** [comment]
Yay!
