### ISSUE TITLE
Household indexing is confusing

### ISSUE THREAD

**Issue by katbusch** [sidewalklabs/doppelganger#27]
Right now households are unique by the (tract, serialno, repeatno) tuple.  They should just have a unique ID

**Comment by katbusch** [comment]
@alexeisw @DavidOry what do you think of just adding a column called household_id to both tables.  
something like this:

```python
persons['household_id'] = persons['tract'].apply(str) + '-' + persons['serial_number'] + '-' + persons['repeat_index']
```

**Comment by alexeisw** [comment]
From a user perspective it'd be great to turn `households['serial_number'] + '-' + households['repeat_index']` into a count. Then households['tract'] + '-' + household['count'] would give clear idea on the index/total number of synthetic HHs within a tract.

**Comment by alexeisw** [comment]
For persons, it'd be great to see a readable ID of 'Tract'-'HH_in_a_tract_idx'-'Person_in_a_household_idx'
